// CommonEnums.idl

namespace WordleWinUI
{
	enum GameStatus
	{
		Unknown,
		InvalidLine,
		InvalidWord,
		Win,
		Lose,
		ThisTurn,
		NextTurn
	};

	enum MessageBoxType
	{
		Unknown,
		Information,
		Exception
	};

	enum MessageBoxIconType
	{
		None,
		Hand,
		Error,
		Stop,
		Question,
		Exclamation,
		Warning,
		Information,
		Asterisk
	};

	enum MessageBoxButtonType
	{
		OK,
		OKCancel,
		RetryCancel,
		YesNo,
		YesNoCancel,
		AbortRetryIgnore
	};
}
