import "Settings.idl";
import "MainViewModel.idl";

namespace WordleWinUI
{
    [default_interface]
    runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
    {
        MainPage();

        MainViewModel ViewModel{ get; };

        Settings ApplicationSettings{ get; };
    }
}
